VISIBLE "Student Information"  
VISIBLE "----------------------------------"  
VISIBLE "Jimothy Student"  
VISIBLE "6969 Denton Street"  
VISIBLE "Boulder, CO 79934"  
VISIBLE "944-555-1044"  
VISIBLE "Junior"  
VISIBLE   
VISIBLE "Parent or Guardian Information"  
VISIBLE "----------------------------------"  
VISIBLE "Martha Student"  
VISIBLE "6969 Denton Street"  
VISIBLE "Boulder, CO 79934"  
VISIBLE "944-555-1044"  
VISIBLE "Boulder ISD"  